<?php
declare(strict_types=1);
require_once __DIR__.'/config/config.php';
header('Content-Type: application/json; charset=utf-8');
header('Access-Control-Allow-Origin: *');
function response(mixed $data = [], ?string $message = null, int $status=200): never { http_response_code($status); echo json_encode(['success'=>$status<400,'data'=>$data,'message'=>$message],JSON_UNESCAPED_UNICODE); exit; }
try {
 $path=trim(parse_url($_SERVER['REQUEST_URI']??'',PHP_URL_PATH) ?? '','/'); $parts=explode('/',$path); $last=$parts[count($parts)-1]??''; $id=ctype_digit($last)?(int)$last:null; $resource=$id!==null?($parts[count($parts)-2]??'productos'):($last==='api.php'?($parts[count($parts)-2]??'productos'):$last); $pdo=db();
 if ($resource==='categorias') response($pdo->query("SELECT idcategoria,nombre FROM categoria WHERE estado=1 ORDER BY nombre")->fetchAll());
 if ($resource==='tiendas') response($pdo->query("SELECT idtienda,nombre,url,logo FROM tienda WHERE estado=1 ORDER BY nombre")->fetchAll());
 if ($resource==='productos' && $id===null) { $q=trim((string)($_GET['q']??'')); $sort=$_GET['sort']??'price'; $order=$sort==='price_desc'?'precio_minimo DESC':($sort==='name'?'p.nombre ASC':'precio_minimo IS NULL,precio_minimo ASC'); $sql="SELECT p.*,m.nombre marca,c.nombre categoria,MIN(pr.precio) precio_minimo,COUNT(DISTINCT pt.idtienda) tiendas FROM producto p LEFT JOIN marca m ON m.idmarca=p.idmarca LEFT JOIN categoria c ON c.idcategoria=p.idcategoria LEFT JOIN producto_tienda pt ON pt.idproducto=p.idproducto AND pt.estado=1 LEFT JOIN precio pr ON pr.idproducto_tienda=pt.idproducto_tienda AND pr.idprecio=(SELECT p2.idprecio FROM precio p2 WHERE p2.idproducto_tienda=pt.idproducto_tienda ORDER BY p2.fecha DESC,p2.idprecio DESC LIMIT 1) WHERE p.estado=1 "; $params=[]; if($q!==''){ $sql.=" AND (p.nombre LIKE :q OR p.modelo LIKE :q OR m.nombre LIKE :q) "; $params['q']="%$q%"; } $sql.=" GROUP BY p.idproducto ORDER BY $order"; $st=$pdo->prepare($sql);$st->execute($params);response($st->fetchAll()); }
 if ($resource==='productos' && $id!==null) { $st=$pdo->prepare("SELECT p.*,m.nombre marca,c.nombre categoria FROM producto p LEFT JOIN marca m ON m.idmarca=p.idmarca LEFT JOIN categoria c ON c.idcategoria=p.idcategoria WHERE p.idproducto=? AND p.estado=1");$st->execute([$id]);$p=$st->fetch();if(!$p)response([], 'Producto no encontrado',404); $s=$pdo->prepare("SELECT pt.*,t.nombre tienda,t.url tienda_url,(SELECT pr.precio FROM precio pr WHERE pr.idproducto_tienda=pt.idproducto_tienda ORDER BY pr.fecha DESC,pr.idprecio DESC LIMIT 1) precio,(SELECT pr.fecha FROM precio pr WHERE pr.idproducto_tienda=pt.idproducto_tienda ORDER BY pr.fecha DESC,pr.idprecio DESC LIMIT 1) actualizado FROM producto_tienda pt LEFT JOIN tienda t ON t.idtienda=pt.idtienda WHERE pt.idproducto=? AND pt.estado=1 ORDER BY precio ASC");$s->execute([$id]);$p['tiendas']=$s->fetchAll();$s=$pdo->prepare("SELECT atributo,valor FROM producto_especificacion WHERE idproducto=? ORDER BY atributo");$s->execute([$id]);$p['especificaciones']=$s->fetchAll();response($p); }
 if ($resource==='precios' && $id!==null) { $st=$pdo->prepare("SELECT t.nombre tienda,pt.url,pr.precio,pr.moneda,pr.disponible,pr.fecha FROM precio pr LEFT JOIN producto_tienda pt ON pt.idproducto_tienda=pr.idproducto_tienda LEFT JOIN tienda t ON t.idtienda=pt.idtienda WHERE pt.idproducto=? ORDER BY pr.precio ASC,pr.fecha DESC");$st->execute([$id]);response($st->fetchAll()); }
 if ($resource==='historial' && $id!==null) { $st=$pdo->prepare("SELECT DATE(pr.fecha) fecha,MIN(pr.precio) precio FROM precio pr LEFT JOIN producto_tienda pt ON pt.idproducto_tienda=pr.idproducto_tienda WHERE pt.idproducto=? GROUP BY DATE(pr.fecha) ORDER BY fecha");$st->execute([$id]);response($st->fetchAll()); }
 response([], 'Ruta no encontrada',404);
} catch (Throwable $e) { error_log($e->getMessage()); response([], 'Error interno del servidor',500); }
